import { useState, useEffect, useRef } from 'react';
import { NavLink } from 'react-router-dom';

import cukaiLogo from '../../assets/cukai-logo.png';
import cukaiBotIcon from '../../assets/cukaibot-icon.png';
import moeLogo from '../../assets/moe-logo.png';
import gamudaLogo from '../../assets/gamuda-logo.png';
import googleCloudLogo from '../../assets/google-cloud-logo.png';
import gamudaAILogo from '../../assets/gamuda-ai-logo.png';

// ── Material Symbol helper ───────────────────────────────────────────────────
const Icon = ({ name, className = '', filled = false }) => (
  <span
    className={`material-symbols-outlined ${className}`}
    style={{ fontVariationSettings: filled ? "'FILL' 1" : "'FILL' 0" }}
  >
    {name}
  </span>
);

// ── FAQ Constant Declarations ───────────────────────────────────────────────────────────
const faqs = [
  { q: 'Is cukai.ai officially recognised by LHDN?', a: 'While cukai.ai is an independent software provider, our algorithms are strictly trained on the Income Tax Act 1967 (ITA 1967) and the latest e-Invoicing guidelines provided by LHDNM. We ensure your outputs are format-compliant for direct submission.' },
  { q: 'How secure is my financial data?', a: 'Your data is stored securely in our CloudSQL PostgreSQL database, isolated and protected with strict access controls. We do not sell or share your data with any third parties. Additional encryption layers are actively being developed and will be rolled out in upcoming releases.' },
  { q: 'Are answers generated by CukaiBot bilingual?', a: 'Yes. CukaiBot is built with native multilingual capabilities. It understands complex tax terminology and can accurately assist you in multiple languages, making compliance accessible for all Malaysian business operators.' },
  { q: 'Does it replace my current accountant?', a: 'No, cukai.ai is designed to complement professional services. It automates the tedious data entry, categorisation and initial compliance checks with algorithmic precision. This frees up your accountant to focus on strategic tax planning and advisory services.' },
  { q: 'What happens if I get audited?', a: 'You are fully prepared. cukai.ai features a 7-year audit-ready account that securely stores all your receipts, invoices and categorisation logic. You can generate comprehensive PDF export reports with a single click to provide a clear, chronological trail for auditors.' },
  { q: 'How long does it take to set up?', a: 'Setup typically takes less than 5 minutes. You simply create an account, upload your receipt documents or data sources and our AI immediately begins structuring your historical data into a compliant format.' },
];

// ── Reusable hook: intersection observer reveal ──────────────────────────────
function useReveal(threshold = 0.1) {
  const ref = useRef(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) { setVisible(true); obs.disconnect(); } },
      { threshold, rootMargin: '0px 0px -40px 0px' }
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, [threshold]);
  return [ref, visible];
}

// ── Static data ─────────────────────────────────────────────────────────────
const brands = ['React JS', 'Python', 'FastAPI', 'PostgreSQL', 'MongoDB', 'Google Cloud', 'Google Gemini'];


function LandingNav() {
  const [scrolled, setScrolled] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);

  useEffect(() => {
    const el = document.getElementById('main-scroll');
    if (!el) return;
    const onScroll = () => setScrolled(el.scrollTop > 60);
    el.addEventListener('scroll', onScroll);
    return () => el.removeEventListener('scroll', onScroll);
  }, []);

  const scrollTo = (id) => {
    setMobileOpen(false);
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <nav className={`fixed top-0 w-full z-50 transition-all duration-300 animate-[fadeInDown_0.5s_cubic-bezier(0.16,1,0.3,1)_forwards] ${scrolled ? 'bg-white/90 backdrop-blur-xl border-b border-slate-200' : ''}`}>
      <div className="flex justify-between items-center max-w-[1280px] mx-auto px-4 md:px-12 h-16">
        <NavLink onClick={() => { document.getElementById('main-scroll')?.scrollTo({ top: 0, behavior: 'smooth' }); }} className="flex items-center gap-2 group">
          <img src={cukaiLogo} alt="cukai.ai logo" className="h-10 w-10 shrink-0" />
          <span className="select-none text-xl font-bold tracking-tight text-[#0F172A]">
            cukai<span className="text-[#10B981]">.</span><span className="font-light text-[#64748B]">ai</span>
          </span>
        </NavLink>

        <div className="hidden md:flex items-center gap-8">
          {[
            { label: 'How It Works', id: 'how-it-works' },
            { label: 'Features', id: 'features' },
            { label: 'Cukai Account', id: 'cukaiaccount' },
            { label: 'Cukai Bot', id: 'cukaibot' },
            { label: 'Pricing', id: 'pricing' },
            { label: 'FAQ', id: 'faq' },
          ].map(({ label, id }) => (
            <button key={id} onClick={() => scrollTo(id)} className="relative text-[#45464D] font-medium text-[15px] hover:text-[#0F172A] transition-colors duration-200 after:content-[''] after:absolute after:w-0 after:h-0.5 after:bottom-[-4px] after:left-1/2 after:bg-[#10B981] after:transition-all after:duration-300 hover:after:w-full hover:after:left-0">
              {label}
            </button>
          ))}
        </div>

        <div className="hidden md:flex items-center gap-6">
          <NavLink to="/login" className="text-[15px] font-medium text-[#64748B] hover:text-[#0F172A] transition-colors">Log In</NavLink>
          <NavLink to="/getstarted" className="bg-[#10B981] hover:bg-emerald-400 text-white font-medium text-[15px] px-5 py-2.5 rounded-lg shadow-[0_4px_14px_rgba(16,185,129,0.35)] hover:shadow-[0_6px_20px_rgba(16,185,129,0.45)] transition-all duration-200 hover:-translate-y-0.5">
            Get Started
          </NavLink>
        </div>

        <button className="md:hidden flex items-center justify-center p-2 text-[#0F172A] hover:bg-slate-100 rounded-lg transition-colors" onClick={() => setMobileOpen(!mobileOpen)}>
          <Icon name={mobileOpen ? 'close' : 'menu'} className="text-[24px]" />
        </button>
      </div>

      {mobileOpen && (
        <div className="md:hidden bg-white border-b border-slate-200 shadow-lg absolute top-16 left-0 w-full animate-[fadeInDown_0.3s_ease_forwards]">
          <div className="flex flex-col px-4 py-4 space-y-4">
            {[
              { label: 'Features', id: 'features' },
              { label: 'How It Works', id: 'how-it-works' },
              { label: 'Cukai Account', id: 'cukaiaccount' },
              { label: 'Cukai Bot', id: 'cukaibot' },
              { label: 'Pricing', id: 'pricing' },
              { label: 'FAQ', id: 'faq' },
            ].map(({ label, id }) => (
              <button key={id} onClick={() => scrollTo(id)} className="text-[#0F172A] font-medium py-2 border-b border-slate-100 text-left">{label}</button>
            ))}
            <div className="pt-4 flex flex-col gap-4">
              <NavLink to="/login" className="text-center font-medium text-[#64748B] py-2">Log In</NavLink>
              <NavLink to="/getstarted" className="bg-[#10B981] text-white text-center font-medium px-5 py-3 rounded-lg shadow-sm">Get Started</NavLink>
            </div>
          </div>
        </div>
      )}
    </nav>
  );
}

// ── cukai.ai Hero ────────────────────────────────────────────────────────────
function Hero() {
  const [ref, visible] = useReveal(0.1);
  const scrollToHow = () => document.getElementById('how-it-works')?.scrollIntoView({ behavior: 'smooth' });

  return (
    /* Main wrapper container */
    <div className="snap-start w-full h-screen flex flex-col justify-between overflow-hidden bg-background relative bg-[linear-gradient(to_right,rgba(15,23,42,.03)_1px,transparent_1px),linear-gradient(to_bottom,rgba(15,23,42,.03)_1px,transparent_1px)] bg-[size:40px_40px]">
      {/* Radial glow background asset */}
      <div className="absolute right-0 top-1/2 -translate-y-1/2 w-[800px] h-[800px] rounded-full -z-10 pointer-events-none bg-[rgba(204,251,241,0.4)] blur-[100px] animate-[pulseRadial_8s_ease-in-out_infinite]" />

      {/* ── Main Hero Section Box ───────────────────────────── */}
      <section
        id="hero"
        className="flex-1 flex flex-col justify-center w-full max-w-[1280px] mx-auto px-6 md:px-12 pt-16"
      >
        {/* Upper Column Content Area */}
        <div className="w-full">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 items-center">
            
            {/* Left column info deck */}
            <div className="lg:col-span-7 flex flex-col gap-4">
              <div className="inline-flex items-center gap-2 bg-[#CCFBF1] text-[#0D9488] px-3 py-1.5 rounded-full w-max opacity-0 animate-[fadeUp_0.6s_cubic-bezier(0.16,1,0.3,1)_forwards]">
                <Icon name="auto_awesome" className="text-sm" filled />
                <span className="text-[12px] font-semibold tracking-wider">AI-Powered Tax Compliance · Malaysia</span>
              </div>

              <h1 className="font-bold text-[#0F172A] leading-[1.1] mt-1 mb-2 text-[clamp(42px,4.8vw,60px)] -tracking-[0.03em]">
                <span className="inline-block opacity-0 animate-[fadeUp_0.6s_cubic-bezier(0.16,1,0.3,1)_80ms_forwards]">
                  Effortless Taxes,
                </span>
                <br />
                <span className="inline-block opacity-0 animate-[fadeUp_0.6s_cubic-bezier(0.16,1,0.3,1)_240ms_forwards]">
                  Powered by
                </span>
                {/* FIX: Explicitly injecting a compiled layout space between inline blocks */}
                {" "}
                <span className="inline-block opacity-0 animate-[fadeUp_0.6s_cubic-bezier(0.16,1,0.3,1)_320ms_forwards] bg-gradient-to-r from-[#10B981] to-[#0D9488] bg-clip-text text-transparent pb-[0.15em]">
                  Intelligence.
                </span>
              </h1>

              <p className="text-base md:text-lg leading-relaxed text-slate-600 max-w-xl opacity-0 mb-2 animate-[fadeUp_0.6s_cubic-bezier(0.16,1,0.3,1)_400ms_forwards]">
                Meet cukai.ai, your dedicated digital tax assistant. We take the complexity out of Malaysian tax compliance by matching your receipts and data seamlessly with the latest LHDN guidelines.
              </p>

              <div className="mb-2 flex flex-col gap-6 opacity-0 animate-[fadeUp_0.6s_cubic-bezier(0.16,1,0.3,1)_560ms_forwards]">
                <div className="flex flex-wrap gap-3">
                  {[
                    { icon: 'verified_user', label: 'Smart Filing' },
                    { icon: 'verified', label: 'AI Insights' },
                    { icon: 'lock', label: 'PDPA Compliant' },
                  ].map(({ icon, label }) => (
                    <div key={label} className="flex items-center gap-1.5 px-3 py-1.5 bg-white border border-slate-200 rounded-full text-xs font-medium text-slate-500 shadow-sm">
                      <Icon name={icon} className="text-[#10B981]" filled />
                      {label}
                    </div>
                  ))}
                </div>
              </div>

              <div className="mt-2 flex flex-col sm:flex-row gap-4 opacity-0 animate-[fadeUp_0.6s_cubic-bezier(0.16,1,0.3,1)_480ms_forwards]">
                <NavLink to="/getstarted" className="h-[48px] px-8 bg-[#10B981] text-white rounded-lg font-medium hover:bg-[#0D9488] transition-all flex items-center justify-center gap-2 shadow-sm hover:-translate-y-0.5">
                  Get Started
                </NavLink>
                <NavLink onClick={scrollToHow} className="h-[48px] px-8 bg-white border border-slate-300 text-slate-900 rounded-lg font-medium hover:bg-slate-50 transition-all flex items-center justify-center border-solid shadow-sm hover:-translate-y-0.5">
                  See How It Works
                </NavLink>
              </div>
            </div>

            {/* Right column — interactive app mockup */}
            <div className="lg:col-span-5 relative hidden lg:block opacity-0 animate-[fadeUp_0.6s_cubic-bezier(0.16,1,0.3,1)_640ms_forwards]">
              <div className="relative w-full h-[420px]">
                
                {/* Main dashboard viewport */}
                <div className="absolute top-1/2 left-1/4 -translate-x-1/12 -translate-y-1/2 w-[310px] rounded-[16px] p-5 z-10 bg-white border border-slate-100 shadow-[0_20px_50px_-12px_rgba(15,23,42,0.06)]">
                  <h3 className="font-semibold text-slate-900 mb-4 flex items-center gap-2 text-sm">
                    <Icon name="monitoring" className="text-slate-400" /> Tax Health Score
                  </h3>
                  <div className="relative w-24 h-24 mx-auto mb-6">
                    <svg className="w-full h-full -rotate-90" viewBox="0 0 100 100">
                      <circle cx="50" cy="50" r="42" fill="none" stroke="#F1F5F9" strokeWidth="8" />
                      <circle cx="50" cy="50" r="42" fill="none" stroke="#10B981" strokeWidth="8" strokeDasharray="264" strokeDashoffset="40" className="transition-all duration-1000 ease-out" />
                    </svg>
                    <div className="absolute inset-0 flex flex-col items-center justify-center">
                      <span className="text-2xl font-bold text-slate-900 tracking-tight">85</span>
                      <span className="text-[9px] text-slate-400 font-bold uppercase tracking-widest mt-0.5">Health</span>
                    </div>
                  </div>
                  <div className="space-y-3">
                    <div className="flex justify-between items-center p-2.5 bg-slate-50 rounded-xl border border-slate-100">
                      <span className="text-xs text-slate-500 font-medium">Saved</span>
                      <span className="font-bold text-[#10B981] text-sm">RM 12,400</span>
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                      <div className="p-2.5 bg-slate-50 rounded-xl border border-slate-100 text-center">
                        <div className="font-bold text-slate-900 text-base">47</div>
                        <div className="text-[11px] text-slate-400 font-medium">Receipts</div>
                      </div>
                      <div className="p-2.5 rounded-xl border border-[#CCFBF1] bg-[rgba(204,251,241,0.2)] text-center relative overflow-hidden">
                        <div className="font-bold text-[#0D9488] text-base">3</div>
                        <div className="text-[11px] text-[#0D9488]/90 font-medium">Reliefs Found</div>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Floating widget card: CukaiBot prompt */}
                <div className="absolute -right-4 top-6 w-[260px] rounded-[14px] p-3.5 z-20 bg-white border border-slate-100/80 shadow-[0_15px_35px_-10px_rgba(15,23,42,0.08)]">
                  <div className="flex gap-2.5 mb-3">
                    <div className="w-6 h-6 rounded-full bg-[#0D9488] flex items-center justify-center flex-shrink-0 shadow-sm">
                      <img src={cukaiBotIcon} alt="CukaiBot Icon" className="h-6 w-6 object-contain" />
                    </div>
                    <div className="text-xs text-slate-600 leading-relaxed pt-0.5">
                      <span className="text-[#0D9488] font-semibold">✦</span> I found 3 unclaimed reliefs worth <strong>RM 2,100</strong>.
                    </div>
                  </div>
                  <div className="flex gap-3 justify-end items-center">
                    <button className="text-[11px] font-semibold text-slate-400 hover:text-slate-600 transition-colors">Review</button>
                    <button className="px-3 py-1.5 text-[11px] font-medium bg-[#0F172A] text-white rounded-md hover:bg-slate-800 transition-colors shadow-sm">Apply All</button>
                  </div>
                </div>

                {/* Floating widget card: Scan details */}
                <div className="absolute left-4 bottom-4 w-[220px] rounded-[14px] p-3.5 z-20 bg-white border border-slate-100/90 shadow-[0_15px_35px_-10px_rgba(15,23,42,0.08)]">
                  <div className="flex justify-between items-center mb-3">
                    <div className="w-8 h-8 rounded-lg bg-slate-50 flex items-center justify-center border border-slate-100">
                      <Icon name="receipt_long" className="text-slate-400 text-sm" />
                    </div>
                    <span className="bg-[#DCFCE7] text-[#15803D] text-[9px] font-bold px-2 py-0.5 rounded-md flex items-center gap-1 uppercase tracking-wider">
                      <Icon name="check" className="text-[10px]" /> Sec 33
                    </span>
                  </div>
                  <div className="space-y-0.5">
                    <div className="text-[11px] font-medium text-slate-400">Kedai Maju Sdn Bhd</div>
                    <div className="text-base font-bold text-slate-900">RM 340.00</div>
                    <div className="text-[10px] font-medium text-slate-400">Deductible Expense</div>
                  </div>
                </div>

              </div>
            </div>

          </div>
        </div>
      </section>

      {/* ── Full-Width Trust Bar Layer ── */}
      <div
        ref={ref}
        className={`w-full h-[76px] bg-white border-t border-slate-200/80 flex items-center overflow-hidden flex-shrink-0 transition-all duration-500 z-30 mt-auto ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-2.5'}`}
      >
        <div className="w-full max-w-[1280px] mx-auto px-4 md:px-12 h-full flex items-center justify-between">
          <div className="flex items-center flex-1 min-w-0 h-full relative">
            <div className="flex-shrink-0 flex items-center pr-6 mr-6 border-r border-slate-200 h-7 z-10">
              <img src={moeLogo} alt="MoE Logo" className="h-20 w-20 object-contain" />
            </div>
            <div className="flex-1 overflow-hidden relative">
              <div className="flex-shrink-0 absolute inset-y-0 left-0 w-8 bg-gradient-to-r from-white to-transparent z-10" />
              <div className="flex-shrink-0 absolute inset-y-0 right-0 w-8 bg-gradient-to-l from-white to-transparent z-10" />
              <div className="flex whitespace-nowrap items-center animate-[marquee_35s_linear_infinite]">
                {[...brands, ...brands].map((b, i) => (
                  <span key={i} className="font-bold text-slate-300 px-6 text-[13px] tracking-wide uppercase">
                    {b}
                    {i < brands.length * 2 - 1 && <span className="ml-6 text-slate-200">·</span>}
                  </span>
                ))}
              </div>
            </div>
          </div>
          <div className="hidden md:flex items-center pl-12 ml-6 flex-shrink-0 space-x-8 z-10 relative before:content-[''] before:absolute before:left-0 before:top-1/2 before:-translate-y-1/2 before:h-6 before:w-px before:bg-slate-200 before:-ml-4">
            <img src={gamudaLogo} alt="Gamuda Logo" className="h-24 w-24 object-contain opacity-80" />
            <span className="w-1 h-1 rounded-full bg-slate-200" />
            <img src={googleCloudLogo} alt="Google Cloud Logo" className="h-28 w-28 object-contain opacity-80" />
            <span className="w-1 h-1 rounded-full bg-slate-200" />
            <img src={gamudaAILogo} alt="Gamuda AI Logo" className="h-16 w-16 object-contain opacity-80" />
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Section Badges ───────────────────────────────────────────────────────────
function AiBadge({ children }) {
  return (
    <span className="inline-flex items-center gap-1 bg-[#CCFBF1] text-[#0D9488] rounded-full px-3 py-1 text-[12px] font-semibold tracking-wide">
      {children}
    </span>
  );
}

// ── Step card sub-component (extracted to respect Rules of Hooks) ────────────
function StepCard({ num, n, icon, color, title, desc, badge, badgeColor, badgeIcon, delay }) {
  const [ref, visible] = useReveal(0.1);
  return (
    <div
      ref={ref}
      className={`flex flex-col items-start text-left group relative bg-white p-6 rounded-xl border border-slate-200 hover:shadow-[0_12px_40px_rgba(15,23,42,0.08)] hover:border-slate-300 hover:-translate-y-1 transition-all duration-700 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-5'}`}
      style={{ transitionDelay: `${delay}ms` }}
    >
      <span className="font-extrabold text-5xl leading-none select-none text-slate-100 mb-3">{num}</span>
      <div className="flex items-center gap-3 mb-3">
        <div className="w-10 h-10 rounded-lg bg-[#E5EEFF] flex items-center justify-center group-hover:scale-110 transition-transform duration-300 flex-shrink-0">
          <Icon name={icon} className={`text-xl`} style={{ color }} filled />
        </div>
        <div className="w-7 h-7 bg-[#0D9488] text-white rounded-full flex items-center justify-center font-bold text-xs shadow-md flex-shrink-0">
          {n}
        </div>
      </div>
      <h3 className="text-base font-semibold text-slate-900 mb-2">{title}</h3>
      <p className="text-sm leading-relaxed text-slate-600 mb-4">{desc}</p>
      <div className="mt-auto inline-flex items-center gap-2 bg-background px-3 py-1.5 rounded-full border border-slate-200/50 text-xs font-medium text-slate-600">
        {badgeIcon && <Icon name={badgeIcon} className="text-xs" />}
        <span style={badgeColor ? { color: badgeColor } : {}}>{badge}</span>
      </div>
    </div>
  );
}


function HowItWorks() {
  const [ref, visible] = useReveal(0.1);

  const steps = [
    { num: '01', n: 1, icon: 'folder', color: '#10B981', title: 'Upload Documents', desc: 'Drag-and-drop your receipts, invoices or profit & loss spreadsheets. Our OCR processes a large range of images and document formats in under 5 seconds.', badge: '⚡ ≤ 5s processing', badgeColor: '#0D9488' },
    { num: '02', n: 2, icon: 'psychology', color: '#0D9488', title: 'AI Classifies & Recommends', desc: 'The AI cross-references ITA Section 33, identifies all eligible reliefs and provides AI insights on your tax profile with full legal citations.', badge: '✦ 95% citation rate', badgeColor: '#0D9488' },
    { num: '03', n: 3, icon: 'web', color: '#10B981', title: 'Instant Tax Summary Reports', desc: 'Generate a complete, audit-ready tax summary with one click. Every figure organised and ready to guide you through your MyTax filing, confidently and accurately.', badge: '🔒 Your data, your control', badgeColor: '#0D9488' },
  ];

  return (
    <section id="how-it-works" className="snap-start h-screen flex flex-col justify-center px-6 md:px-12 py-10 bg-background overflow-hidden">
      <div className="max-w-[1280px] mx-auto w-full flex flex-col gap-6">
        <div ref={ref} className={`flex flex-col items-center text-center max-w-3xl mx-auto transition-all duration-700 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-5'}`}>
          <AiBadge>✦ The Process</AiBadge>
          <h2 className="text-[clamp(22px,3vw,36px)] font-bold text-slate-900 mt-4 mb-3 leading-tight tracking-tight">
            From receipt to filed return — in three steps.
          </h2>
          <p className="text-[clamp(13px,1.5vw,16px)] leading-relaxed text-slate-600">Most users complete their first tax profile in under 5 minutes.</p>
        </div>

        <div className="relative">
          <div className="hidden md:block absolute top-[104px] left-[calc(16.66%+16px)] right-[calc(16.66%+16px)] h-[2px] z-0">
            <svg height="2" width="100%"><line stroke="#E2E8F0" strokeWidth="2" strokeDasharray="10,10" x1="0" x2="100%" y1="1" y2="1" /></svg>
            <div className="absolute top-1/2 -translate-y-1/2 w-3 h-3 bg-[#0D9488] rounded-full left-0 shadow-[0_0_10px_#0D9488] animate-[slideDot_6s_infinite_ease-in-out]" />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 relative z-10">
            {steps.map(({ num, n, icon, color, title, desc, badge, badgeColor, badgeIcon }, i) => (
              <StepCard key={n} num={num} n={n} icon={icon} color={color} title={title} desc={desc} badge={badge} badgeColor={badgeColor} badgeIcon={badgeIcon} delay={i * 100} />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

// ── Section 2: Features ──────────────────────────────────────────────────────
function FeatureCard({ children, delay = 0, dark = false, className = '', id, borderLeft = false }) {
  const [ref, visible] = useReveal(0.1);
  const base = 'rounded-[12px] p-3 border';
  const light = 'bg-white border-slate-200 hover:shadow-[0_12px_40px_rgba(15,23,42,0.08)] hover:border-slate-300 hover:-translate-y-1';
  const darkCls = 'bg-[#0F172A] text-white border-[#1E293B] hover:border-[#334155] hover:shadow-[0_20px_40px_rgba(0,0,0,0.2)] hover:-translate-y-1';

  return (
    <div
      ref={ref}
      id={id}
      className={`${base} ${dark ? darkCls : light} ${borderLeft ? 'border-l-[3px] border-l-state-300 hover:border-l-[#0D9488]' : ''} ${className} transition-[opacity,transform,box-shadow,border-color] duration-500 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-5'}`}
      style={{ transitionDelay: `${delay}ms` }}
    >
      {children}
    </div>
  );
}

function Features() {
  const [ref, visible] = useReveal(0.05);

  return (
    <section id="features" className="snap-start h-screen flex flex-col justify-center px-6 md:px-12 pt-16 bg-background overflow-hidden">
      <div className="max-w-[1280px] mx-auto w-full flex flex-col gap-6">

        {/* header block */}
        <div ref={ref} className={`text-center max-w-3xl mx-auto transition-all duration-700 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-5'}`}>
          <AiBadge>✦ The Features</AiBadge>
          <h2 className="text-[clamp(22px,3vw,36px)] font-bold text-slate-900 mt-4 mb-2 tracking-tight leading-tight">
            Everything you need for tax compliance — in one platform.
          </h2>
          <p className="text-[clamp(12px,1.4vw,15px)] leading-relaxed text-slate-800">
            Built specifically for Malaysian SMEs for sole proprietors and partnerships. Every feature is grounded in LHDN guidelines and the ITA 1967.
          </p>
        </div>

        {/* cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">

          {/* Card 1: CukaiAccount */}
          <FeatureCard delay={80} className="md:col-span-1 md:row-span-2 flex flex-col justify-between" borderLeft>
            <div>
              <AiBadge>✦ CukaiAccount</AiBadge>
              <h3 className="text-[#0F172A] mb-1.5 mt-1.5 text-base font-semibold">Scan. Upload. Classify.</h3>
              <p className="text-sm text-[#475569] mb-2 leading-relaxed">
                Upload JPG, PNG, or PDF receipts. Our OCR engine extracts vendor, date and amount - then the AI classifies each expense under Section 33 of the ITA.
              </p>
              <ul className="space-y-1.5 mb-2">
                {['Batch upload your receipts', 'Confidence score per classification', '7-year secure storage for LHDN audits'].map((item) => (
                  <li key={item} className="flex items-center gap-2 text-slate-700 text-sm">
                    <Icon name="check_circle" className="text-[#0D9488]" filled /> {item}
                  </li>
                ))}
              </ul>
            </div>
            <div className="bg-[#F8FAFC] border border-slate-200 rounded-lg p-2.5 mt-auto">
              <div className="flex items-center justify-between mb-1.5">
                <div className="h-6 w-6 bg-gray-200 rounded flex-shrink-0" />
                <div className="flex-1 ml-2">
                  <div className="h-2 w-16 bg-gray-300 rounded mb-1" />
                  <div className="h-1.5 w-10 bg-gray-200 rounded" />
                </div>
                <div className="font-mono text-xs font-medium">RM 145.00</div>
              </div>
              <div className="border-t border-dashed border-slate-300 my-1.5" />
              <div className="inline-flex items-center gap-1 bg-green-50 text-green-700 text-xs font-medium px-2 py-0.5 rounded border border-green-200">
                <Icon name="check" /> Deductible · 94% confidence
              </div>
            </div>
          </FeatureCard>

          {/* Card 2: Cukai Bot */}
          <FeatureCard delay={80} className="flex flex-col justify-between" borderLeft>
            <div>
              <AiBadge>✦ CukaiBot</AiBadge>
              <h3 className="text-[#0F172A] mb-1.5 mt-1.5 text-base font-semibold">Rojak mixed-laguage chat bot</h3>
              <p className="text-sm text-[#475569] mb-2 leading-relaxed">
                Conversational AI grounded in the ITA 1967 with appopriate citations of exact sections.
              </p>
            </div>
            <div className="bg-[#F1F5F9] rounded-lg p-2.5 text-xs">
              <div className="text-right text-[#475569] mb-1.5">"Ada relief untuk medical expenses?"</div>
              <div className="text-left text-[#0D9488] font-medium flex items-start gap-1">
                <div className="w-6 h-6 rounded-full bg-[#0D9488] flex items-center justify-center flex-shrink-0 shadow-sm">
                  <img src={cukaiBotIcon} alt="CukaiBot Icon" className="h-6 w-6 object-contain" />
                </div> "Yes, up to RM 10,000..."
              </div>
            </div>
          </FeatureCard>

          {/* Card 3: AI Insights */}
          <FeatureCard delay={80} className="flex flex-col justify-between" borderLeft>
            <div>
              <AiBadge>✦ AI Insights & Recommendations</AiBadge>
              <h3 className="text-[#0F172A] mb-1.5 mt-1.5 text-base font-semibold">Never miss a deduction</h3>
              <p className="text-sm text-[#475569] mb-2 leading-relaxed">
                Analyses income and expenses to surface ALL eligible tax reliefs - personal, lifestyle, medical, EPF.
              </p>
            </div>
            <div className="bg-[#F1F5F9] rounded-lg p-2.5 text-xs">
              <div className="flex mt-2.5 mb-2.5 gap-2.5 justify-items-center items-center">
                <div className="text-xs text-slate-600 leading-relaxed pt-0.5">
                  <span className="text-[#0D9488] font-semibold">✦</span> I found 3 unclaimed reliefs worth <strong>RM 2,100</strong>.
                </div>
                <button className="px-3 py-1.5 text-[11px] font-medium bg-[#0F172A] text-white rounded-md hover:bg-slate-800 transition-colors shadow-sm">Review</button>
              </div>
            </div>
          </FeatureCard>

          {/* Card 4: Multi Account Profiles */}
          <FeatureCard delay={80} dark borderLeft>
            <AiBadge>✦ Multi-Account Profiles</AiBadge>
            <h3 className="text-white mb-1.5 mt-1.5 text-base font-semibold">One dashboard for each business</h3>
            <p className="text-sm text-slate-400 leading-relaxed">
              Manage multiple business tax profiles under a single login switching between accounts instantly.
            </p>
          </FeatureCard>

          {/* Card 5: e-Invoice Engine */}
          <FeatureCard delay={80} dark borderLeft>
            <AiBadge>✦ Documentation</AiBadge>
            <h3 className="text-white mb-1.5 mt-1.5 text-base font-semibold">Guides, docs, and API reference</h3>
            <p className="text-sm text-slate-500 leading-relaxed">
              From onboarding guides to full API documentation, clear references are available at every step.
            </p>
          </FeatureCard>
        </div>
      </div>
    </section>
  );
}

// ── Section 4: CukaiAccount Showcase ──────────────────────────────────────────────
function ShowcaseReveal({ children }) {
  const [ref, visible] = useReveal(0.1);
  return (
    <div ref={ref} className={`transition-all duration-700 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-5'}`}>
      {children}
    </div>
  );
}

function CukaiAccountShowcase() {
  return (
    <section
      id="cukaiaccount"
      className="snap-start h-screen flex flex-col justify-center px-6 md:px-12 py-10 bg-[#0F172A] text-white relative overflow-hidden"
    >
      <div className="absolute inset-0 opacity-10 pointer-events-none bg-[radial-gradient(ellipse_at_center,#86F2E4_0%,transparent_70%)]" />

      <div className="max-w-[1280px] mx-auto w-full relative z-10 flex flex-col gap-3">

        {/* Header */}
        <div className="text-center max-w-3xl mx-auto opacity-0 animate-[fadeUp_0.6s_cubic-bezier(0.16,1,0.3,1)_80ms_forwards]">
          <AiBadge>✦ Cukai Account</AiBadge>
          <h2 className="text-[clamp(22px,3vw,36px)] font-bold text-white mt-4 mb-2 leading-tight tracking-tight">
            Personalise your Cukai Account.
          </h2>
          <p className="text-[clamp(12px,1.4vw,15px)] text-[#7C839B]">
            Audit-ready records, organised by AI — stored for the full 7-year LHDN window.
          </p>
        </div>

        {/* Body — 50/50 split */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-3 items-center w-full">

          {/* Left — Receipt Mockup */}
          <ShowcaseReveal delay={160}>
            <div className="w-full flex flex-col justify-center">
              <div className="rounded-xl shadow-2xl overflow-hidden p-5 bg-[rgba(30,41,59,0.8)] backdrop-blur-[12px] border border-white/10 animate-[float_6s_ease-in-out_infinite] w-full flex flex-col">
                <div className="flex items-center justify-between mb-4 pb-3 border-b border-white/10">
                  <h3 className="text-base font-semibold text-white leading-tight">Recent Receipts</h3>
                  <div className="flex items-center gap-3">
                    <div className="rounded-lg px-2.5 py-1.5 flex items-center gap-2 border border-white/10 bg-white/5">
                      <div className="relative w-7 h-7 flex-shrink-0">
                        <svg className="w-full h-full -rotate-90" viewBox="0 0 36 36">
                          <path
                            d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                            fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="4"
                          />
                          <path
                            d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                            fill="none" stroke="#89F5E7" strokeDasharray="85, 100" strokeWidth="4"
                          />
                        </svg>
                        <div className="absolute inset-0 flex items-center justify-center">
                          <span className="font-mono text-[7px] text-white">85%</span>
                        </div>
                      </div>
                      <div>
                        <p className="text-[9px] font-semibold uppercase tracking-wider text-[#76777D] leading-tight">Confidence</p>
                        <p className="text-[11px] font-medium text-white leading-tight">Classification</p>
                      </div>
                    </div>
                    <Icon name="filter_list" className="text-[#76777D]" />
                  </div>
                </div>
                <div className="space-y-2.5 flex-1 flex flex-col justify-center">
                  {[
                    { icon: 'storefront', name: 'Mydin Holdings', amt: 'RM 234.50', status: 'Deductible', cls: 'bg-[#006A61]/20 text-[#89F5E7] border-[#006A61]/30', statusIcon: 'check' },
                    { icon: 'directions_car', name: 'Grab', amt: 'RM 45.00', status: 'Mixed-Use', cls: 'bg-[#F59E0B]/20 text-[#FCD34D] border-[#F59E0B]/30', statusIcon: 'warning' },
                    { icon: 'local_parking', name: 'Parking DBKL', amt: 'RM 12.00', status: 'Non-Deductible', cls: 'bg-red-900/20 text-red-300 border-red-700/30', statusIcon: 'close' },
                  ].map(({ icon, name, amt, status, cls, statusIcon }) => (
                    <div key={name} className="flex items-center justify-between p-3 rounded-lg bg-white/5 border border-white/5 hover:bg-white/10 transition-colors">
                      <div className="flex items-center gap-3">
                        <div className="w-9 h-9 rounded bg-[#0F172A] flex items-center justify-center border border-white/10 flex-shrink-0">
                          <Icon name={icon} className="text-white text-[16px]" />
                        </div>
                        <div>
                          <p className="text-[14px] font-medium text-white">{name}</p>
                          <p className="font-mono text-[11px] text-[#76777D]">{amt}</p>
                        </div>
                      </div>
                      <div className={`flex items-center gap-1 px-2 py-1 rounded border text-[10px] font-semibold whitespace-nowrap w-[110px] justify-center ${cls}`}>
                        <Icon name={statusIcon} /> {status}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </ShowcaseReveal>

          {/* Right — Text */}
          <ShowcaseReveal delay={320}>
            <div className="flex flex-col justify-center h-full space-y-4">
              <p className="text-[clamp(13px,1.4vw,16px)] leading-relaxed text-[#76777D]">
                Never fear an LHDN audit again. Just scan and upload your receipts and documents. Our AI automatically extracts data, categorises expenses, calculates deductibility and stores a compliant PDF in your cukai account for the legally required 7 years.
              </p>
              <ul className="space-y-2.5 text-sm text-[#76777D] leading-relaxed">
                {[
                  { bold: 'Upload scan:', text: ' JPG, PNG, PDF receipts or documents processed easily.' },
                  { bold: 'AI classification:', text: ' Expenses categorised with confidence automatically.' },
                  { bold: '7-year storage:', text: ' Compliant records retained for the full LHDN audit window.' },
                ].map(({ bold, text }) => (
                  <li key={bold} className="flex items-start gap-2.5">
                    <Icon name="check_circle" className="text-[#006A61] mt-0.5 flex-shrink-0" />
                    <span><strong className="text-white">{bold}</strong>{text}</span>
                  </li>
                ))}
              </ul>
            </div>
          </ShowcaseReveal>

        </div>
      </div>
    </section>
  );
}


// ── Section 3: CukaiBot Showcase ──────────────────────────────────────────────
function CukaiBotShowcase() {
  return (
    <section
      id="cukaibot"
      className="snap-start bg-background h-screen flex flex-col justify-center px-6 md:px-12 pt-16 bg-[#F8FAFC] relative overflow-hidden"
    >
      <div className="absolute top-0 right-0 w-1/2 h-full bg-gradient-to-l from-[#EFF4FF] to-transparent opacity-50 pointer-events-none" />

      <div className="max-w-[1280px] mx-auto w-full relative z-10 flex flex-col gap-3">

        {/* Header */}
        <div className="text-center max-w-3xl mx-auto opacity-0 animate-[fadeUp_0.6s_cubic-bezier(0.16,1,0.3,1)_80ms_forwards]">
          <AiBadge>✦ Cukai Bot</AiBadge>
          <h2 className="text-[clamp(22px,3vw,36px)] font-bold text-slate-900 mt-4 mb-2 leading-tight tracking-tight">
            Ask your tax questions in any language.
          </h2>
          <p className="text-[clamp(12px,1.4vw,15px)] text-slate-600">
            Grounded strictly in ITA 1967 — accurate, source-cited answers in seconds.
          </p>
        </div>

        {/* Body — 50/50 split */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-3 items-center w-full">

          {/* Left — Text */}
          <ShowcaseReveal>
            <div className="flex flex-col justify-center h-full space-y-4">
              <p className="text-[clamp(13px,1.4vw,16px)] leading-relaxed text-slate-600">
                Meet CukaiBot, your dedicated tax assistant. Grounded strictly in ITA 1967 and current LHDN guidelines, it provides accurate source-cited answers to complex queries in seconds.
              </p>
              <ul className="space-y-2.5 text-sm text-slate-600 leading-relaxed">
                {[
                  { bold: 'Multilingual Support:', text: ' Converse fluently in multiple languages.' },
                  { bold: 'Cites Sections:', text: ' Every claim is backed by specific legal references.' },
                  { bold: 'Zero-hallucination:', text: ' Strict grounding architecture ensures 100% compliance.' },
                ].map(({ bold, text }) => (
                  <li key={bold} className="flex items-start gap-2.5">
                    <Icon name="check_circle" className="text-[#006A61] mt-0.5 flex-shrink-0" />
                    <span><strong>{bold}</strong>{text}</span>
                  </li>
                ))}
              </ul>
            </div>
          </ShowcaseReveal>

          {/* Right — Chat Mockup */}
          <ShowcaseReveal delay={160}>
            <div className="relative w-full flex flex-col justify-center pb-8 animate-[float_6s_ease-in-out_infinite]">
              <div className="bg-white rounded-xl shadow-[0px_10px_15px_-3px_rgba(15,23,42,0.08)] border border-slate-200 overflow-hidden flex flex-col h-[400px]">
                <div className="flex items-center justify-between px-6 py-3 border-b border-slate-200 bg-white">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-[#131b2e] flex items-center justify-center">
                      <img src={cukaiBotIcon} alt="CukaiBot Icon" className="h-8 w-8 object-contain" />
                    </div>
                    <div>
                      <h4 className="text-[12px] font-semibold text-[#0F172A] flex items-center gap-1">
                        CukaiBot <Icon name="verified" className="text-[#0D9488]" filled />
                      </h4>
                      <div className="flex items-center gap-1">
                        <div className="w-2 h-2 rounded-full bg-[#006A61]" />
                        <span className="font-mono text-[12px] text-[#45464D]">Online</span>
                      </div>
                    </div>
                  </div>
                  <Icon name="more_horiz" className="text-[#76777D]" />
                </div>
                <div className="flex-1 overflow-y-auto p-5 space-y-4 bg-white">
                  <div className="flex justify-end">
                    <div className="bg-[#0F172A] text-white rounded-lg rounded-tr-none px-2 py-1 max-w-[85%] text-sm leading-relaxed">
                      Ada ke relief untuk anak pergi universiti?
                    </div>
                  </div>
                  <div className="flex justify-start">
                    <div className="bg-white border border-slate-200 shadow-sm rounded-lg rounded-tl-none px-2 py-1 max-w-[90%] text-sm leading-relaxed text-[#0b1c30]">
                      <p className="mb-2">Ya! Di bawah Seksyen 46(1)(b), pelepasan sehingga RM 8,000 dibenarkan untuk anak berumur 18 tahun ke atas yang mengikuti pengajian tinggi sepenuh masa.</p>
                      <button className="inline-flex items-center gap-1 text-xs font-mono text-[#006A61] hover:text-[#005236] transition-colors border border-[#006A61]/20 rounded px-2 py-1 bg-[#006A61]/5 mt-1">
                        <Icon name="policy" /> Verify Source
                      </button>
                    </div>
                  </div>
                  <div className="flex justify-end">
                    <div className="bg-[#0F172A] text-white rounded-lg rounded-tr-none px-2 py-1 max-w-[85%] text-sm leading-relaxed">
                      What about medical expenses?
                    </div>
                  </div>
                  <div className="flex justify-start">
                    <div className="bg-white border border-slate-200 shadow-sm rounded-lg rounded-tl-none px-2 py-1 max-w-[90%] text-sm leading-relaxed text-[#0b1c30]">
                      <p className="mb-2">Under S.46(1)(d), medical expenses for serious illness are claimable up to RM 10,000. This limit also includes full medical examination up to RM 1,000.</p>
                      <button className="inline-flex items-center gap-1 text-xs font-mono text-[#006A61] hover:text-[#005236] transition-colors border border-[#006A61]/20 rounded px-2 py-1 bg-[#006A61]/5 mt-1">
                        <Icon name="policy" /> Verify Source
                      </button>
                    </div>
                  </div>
                </div>
                <div className="p-3 bg-white border-t border-slate-200">
                  <div className="relative">
                    <input
                      disabled
                      placeholder="Ask a tax question..."
                      className="w-full bg-[#F1F5F9] rounded-lg py-2.5 px-3 pr-12 text-sm text-[#0b1c30] focus:ring-2 focus:ring-[#0F172A] outline-none transition-all"
                    />
                    <button className="absolute right-2 top-1/2 -translate-y-1/2 w-8 h-8 flex items-center justify-center text-[#0F172A] hover:text-[#0F172A]/80 transition-colors">
                      <Icon name="send" />
                    </button>
                  </div>
                </div>
              </div>
              <div className="absolute bottom-0 left-1/2 -translate-x-1/2 flex gap-3 whitespace-nowrap">
                {['3 Languages', '95% Cited', '< 3s Response'].map((t, i) => (
                  <div key={t} className="bg-white/90 backdrop-blur-md px-3 py-1.5 rounded-full font-mono text-xs text-[#0b1c30] shadow-sm border border-slate-200 flex items-center gap-1">
                    {i === 1 && <Icon name="check_circle" className="text-[#006A61]" />}
                    {i === 2 && <Icon name="bolt" className="text-[#0D9488]" />}
                    {t}
                  </div>
                ))}
              </div>
            </div>
          </ShowcaseReveal>

        </div>
      </div>
    </section>
  );
}

// ── Section 5: Pricing ───────────────────────────────────────────────────────
function PriceCard({ plan, annual, featured = false, index }) {
  const plans = {
    free: {
      name: 'Free Forever', price: 'RM 0', period: '/mo',
      desc: 'Perfect for freelancers.',
      features: ['5 receipt uploads/mo', '5 report generation/mo', '3 Account Profiles', 'Basic CukaiBot', 'Basic AI Insight'],
      cta: 'Get Started Free', ctaStyle: 'border-2 border-[#0F172A] text-[#0F172A] hover:bg-[#E5EEFF]',
    },
    pro: {
      name: 'SME Pro', price: annual ? 'RM 47' : 'RM 59', period: '/mo',
      desc: 'The standard for growing businesses.',
      features: ['Unlimited uploads', 'Unlimited report generation', '20 Account Profiles', 'Advanced CukaiBot', 'Advanced AI Insight'],
      cta: 'Start 14-Day Free Trial', ctaStyle: 'bg-[#0F172A] text-white hover:bg-[#1E293B]',
    },
    enterprise: {
      name: 'Enterprise', price: 'Custom', period: '',
      desc: 'For large scale operations.',
      features: ['Pro Subscription Features', 'Multi-branch support', 'Dedicated Account Manager', 'API Automation', 'Custom LHDN Reporting'],
      cta: 'Contact Sales', ctaStyle: 'border-2 border-slate-200 text-[#0b1c30] hover:border-[#0F172A] hover:text-[#0F172A]',
    },
  };

  const p = plans[plan];
  const [ref, visible] = useReveal(0.1);

  return (
    <div
      ref={ref}
      className={`rounded-xl p-4 flex flex-col justify-between h-full relative transition-all duration-500 ${
        featured 
          ? 'bg-[#131b2e] border border-transparent shadow-xl z-10 md:scale-[1.02]' 
          : 'bg-white border border-slate-200 hover:shadow-[0_12px_32px_rgba(15,23,42,0.06)] hover:border-slate-300'
      } hover:-translate-y-1 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'}`}
      style={{ transitionDelay: `${index * 80}ms` }}
    >
      {/* Featured Pill */}
      {featured && (
        <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-[#4EDEA3] text-[#002113] px-3 py-0.5 rounded-full text-[11px] font-semibold flex items-center gap-1 shadow-sm whitespace-nowrap">
          <Icon name="star" filled className="text-xs" /> Most Popular
        </div>
      )}

      {/* Content Top */}
      <div className="flex flex-col flex-grow">
        {/* Header Info */}
        <div className="mb-2">
          <h3 className={`text-base font-bold leading-tight ${featured ? 'text-white' : 'text-[#0b1c30]'}`}>{p.name}</h3>
          <div className="mt-1 flex items-baseline gap-1">
            <span className={`text-4xl font-bold leading-none ${featured ? 'text-white' : 'text-slate-900'}`}>{p.price}</span>
            {p.period && <span className={`text-xs font-medium ${featured ? 'text-[#7C839B]' : 'text-slate-600'}`}>{p.period}</span>}
          </div>
          <p className={`text-xs leading-snug mt-1.5 ${featured ? 'text-[#8E97B3]' : 'text-slate-600'}`}>{p.desc}</p>
        </div>

        {/* Separator */}
        <hr className={`mb-3 ${featured ? 'border-[#7C839B]/20' : 'border-slate-100'}`} />

        {/* Feature Checklist - Compact item row gaps */}
        <ul className="space-y-1 mb-2 flex-grow">
          {p.features.map((f) => (
            <li key={f} className="flex items-center gap-2 text-left">
              <Icon 
                name="check_circle" 
                className={`flex-shrink-0 text-sm ${featured ? 'text-[#4EDEA3]' : 'text-[#10B981]'}`} 
                filled
              />
              <span className={`text-xs leading-tight ${featured ? 'text-slate-300' : 'text-slate-700'}`}>{f}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

function Pricing() {
  const [annual, setAnnual] = useState(true);
  const [ref, visible] = useReveal(0.1);

  return (
    <section id="pricing" className="snap-start h-screen flex flex-col justify-center px-6 md:px-12 py-10 bg-background overflow-hidden">
      <div className="max-w-[1280px] mx-auto w-full flex flex-col gap-5">
        
        {/* Title Group */}
        <div ref={ref} className={`flex flex-col items-center text-center max-w-3xl mx-auto transition-all duration-700 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-3'}`}>
          <AiBadge>✦ The Pricing</AiBadge>
          <h2 className="text-[clamp(22px,3vw,36px)] font-bold text-slate-900 mt-6 mb-1.5 leading-tight tracking-tight">
            Simple, transparent pricing
          </h2>
          <p className="text-[clamp(12px,1.4vw,14px)] text-slate-600">Built for Malaysian SMEs, freelancers, and growing teams.</p>
          
          {/* Toggle Switch */}
          <div className="inline-flex items-center mt-3 p-1 bg-[#E2E8F0] rounded-full border border-slate-200/60">
            <button 
              onClick={() => setAnnual(false)} 
              className={`px-4 py-1 rounded-full text-[11px] font-bold transition-all duration-200 ${!annual ? 'bg-white shadow-sm text-[#0F172A]' : 'text-[#64748B] hover:text-[#0F172A]'}`}
            >
              Monthly
            </button>
            <button 
              onClick={() => setAnnual(true)} 
              className={`px-4 py-1 rounded-full text-[11px] font-bold flex items-center gap-1.5 transition-all duration-200 ${annual ? 'bg-white shadow-sm text-[#0F172A]' : 'text-[#64748B] hover:text-[#0F172A]'}`}
            >
              Annual <span className="bg-[#10B981]/10 text-[#047857] px-1.5 py-0.5 rounded-full text-[8px] font-bold">Save 20%</span>
            </button>
          </div>
        </div>

        {/* Pricing Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-5 items-stretch w-full max-w-6xl mx-auto relative z-10">
          <PriceCard plan="free" annual={annual} index={0} />
          <PriceCard plan="pro" annual={annual} featured index={1} />
          <PriceCard plan="enterprise" annual={annual} index={2} />
        </div>

        {/* Footer note */}
        <div className="text-center flex items-center justify-center gap-1.5 text-[#64748B] font-medium text-[11px] tracking-wide">
          <Icon name="lock" className="text-xs" />
          <span>No credit card required. Cancel anytime. 100% PDPA compliant.</span>
        </div>
      </div>
    </section>
  );
}

// ── Section 6: FAQ ───────────────────────────────────────────────────────────
function FAQ() {
  const [open, setOpen] = useState(null);
  const [ref, visible] = useReveal(0.1);
  const left = faqs.slice(0, 3);
  const right = faqs.slice(3);

  return (
    <section id="faq" className="snap-start h-screen flex flex-col justify-center px-6 md:px-12 py-10 bg-background overflow-hidden">
      <div className="max-w-[1280px] mx-auto w-full flex flex-col gap-6">
        
        {/* Title Group */}
        <div ref={ref} className={`flex flex-col items-center text-center max-w-3xl mx-auto transition-all duration-700 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-3'}`}>
          <AiBadge>✦ Support & FAQ</AiBadge>
          <h2 className="text-[clamp(22px,3vw,36px)] font-bold text-slate-900 mt-7 mb-2 leading-tight tracking-tight">
            Everything you need to know about AI-powered compliance.
          </h2>
          <p className="text-[clamp(12px,1.4vw,14px)] text-slate-600">Common questions from Malaysian SMEs and business owners.</p>
        </div>
        {/* FAQ Layout Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-6xl mx-auto w-full relative z-10">
          {[left, right].map((col, ci) => (
            <div key={ci} className="space-y-4">
              {col.map((item, idx) => {
                const key = ci * 3 + idx;
                const isOpen = open === key;
                return (
                  <div
                    key={key}
                    className={`bg-white border border-slate-200 rounded-xl overflow-hidden cursor-pointer transition-all duration-200 hover:shadow-md ${isOpen ? 'shadow-sm' : ''}`}
                    onClick={() => setOpen(isOpen ? null : key)}
                  >
                    {/* Upscaled header padding (p-5) and typography (text-[15px]) */}
                    <div className="flex justify-between items-center p-5">
                      <h3 className="text-sm font-bold text-slate-900 leading-snug pr-4">{item.q}</h3>
                      <Icon
                        name="expand_more"
                        className={`flex-shrink-0 text-xl transition-transform duration-300 ${isOpen ? 'rotate-180 text-[#009668]' : 'text-[#76777D]'}`}
                      />
                    </div>
                    {/* Balanced fluid expansion drawer with elevated text base metrics */}
                    <div className={`overflow-hidden transition-all duration-300 ${isOpen ? 'max-h-[300px] opacity-100 pb-5' : 'max-h-0 opacity-0 pb-0'}`}>
                      <p className="px-5 text-slate-600 text-sm leading-relaxed">{item.a}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ── Final CTA + Footer ───────────────────────────────────────────────────────
function FinalCTA() {
  const [ref, visible] = useReveal(0.1);

  return (
    <section className="px-6 md:px-12 py-12 max-w-[1280px] mx-auto relative overflow-hidden">
      <div className="bg-[#131b2e] rounded-[24px] relative overflow-hidden shadow-2xl">
        <div className="absolute inset-0 pointer-events-none bg-[radial-gradient(circle_at_0%_0%,rgba(107,216,203,0.15)_0%,transparent_50%),radial-gradient(circle_at_100%_100%,rgba(78,222,163,0.1)_0%,transparent_50%)]" />
        <div ref={ref} className={`relative z-10 py-20 px-4 md:px-12 flex flex-col items-center text-center max-w-4xl mx-auto transition-all duration-700 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-5'}`}>
          <div className="inline-flex items-center gap-1 px-3 py-1.5 rounded-full bg-[#CCFBF1] mb-4 border border-[#99F6E4]">
            <Icon name="magic_button" className="text-[#0D9488]" filled />
            <span className="text-[12px] font-semibold text-[#0D9488] tracking-wide">AI-Powered Compliance</span>
          </div>
          <h2 className="text-3xl font-bold text-white mb-3 leading-tight tracking-tight">
            Ready to make tax season your competitive advantage?
          </h2>
          <p className="text-xs font-semibold leading-relaxed text-[#7C839B] mb-4">
            Be the first few Malaysian businesses to be automating their compliance. It takes less than 5 minutes.
          </p>
          <div className="flex flex-col sm:flex-row gap-6 items-center w-full sm:w-auto mb-3">
            <NavLink to="/getstarted" className="w-full sm:w-auto bg-white text-[#131b2e] text-xs font-semibold px-6 py-3 rounded-lg hover:bg-[#EFF4FF] transition-all duration-200 shadow-md hover:-translate-y-1">
              Get Started
            </NavLink>
          </div>
          <div className="flex items-center gap-1 text-[#7C839B] opacity-80">
            <Icon name="verified" />
            <span className="text-[12px] font-semibold">No Credit Card Required • Verified Savings</span>
          </div>
        </div>
      </div>
    </section>
  );
}

function Footer() {
  const scrollTo = (id) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });

  return (
    <footer className="bg-[#131b2e] text-[#7C839B] w-full text-[14px] leading-normal">
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 max-w-[1280px] mx-auto px-6 md:px-12 py-4">
        
        {/* Brand Column */}
        <div className="col-span-1 md:col-span-3 pr-1 flex flex-col gap-4">
          <div className="flex items-center gap-2">
            <img src={cukaiLogo} alt="cukai.ai logo" className="h-8 w-8 shrink-0 -ml-1" />
            <span className="select-none text-lg font-bold tracking-tight text-white">
              cukai<span className="text-[#10B981]">.</span><span className="font-light text-[#64748B]">ai</span>
            </span>
          </div>
          <p className="text-[#7C839B]/80 max-w-sm text-[13px] leading-relaxed">
            Automating tax compliance for Malaysian SMEs<br />with precision and institutional trust.
          </p>
          <div className="mt-auto pt-3 flex flex-col gap-0.5">
            <p className="text-[#7C839B]/60 text-xs">© 2026 cukai.ai. All rights reserved.</p>
            <p className="text-[#4EDEA3] text-xs font-medium flex items-center gap-1">Proudly made for Malaysian SMEs</p>
          </div>
        </div>

        {/* Product Column - Added md:pl-6 to push content slightly right on desktop */}
        <div className="flex flex-col gap-2 md:pl-40">
          <h4 className="text-[11px] font-bold uppercase tracking-wider text-white mb-0.5">Product</h4>
          <button onClick={() => scrollTo('how-it-works')} className="text-[#7C839B]/80 hover:text-[#6FFBBE] transition-colors text-left text-[13px]">How It Works</button>
          <button onClick={() => scrollTo('features')} className="text-[#7C839B]/80 hover:text-[#6FFBBE] transition-colors text-left text-[13px]">Features</button>
          <button onClick={() => scrollTo('pricing')} className="text-[#7C839B]/80 hover:text-[#6FFBBE] transition-colors text-left text-[13px]">Pricing</button>
          <button onClick={() => scrollTo('cukaiaccount')} className="text-[#7C839B]/80 hover:text-[#6FFBBE] transition-colors text-left text-[13px]">Cukai Account</button>
          <button onClick={() => scrollTo('cukaibot')} className="text-[#7C839B]/80 hover:text-[#6FFBBE] transition-colors text-left text-[13px]">Cukai Bot</button>
        </div>     
      </div>
    </footer>
  );
}

function Home() {
  return (
    <>
      <LandingNav />
      <div id="main-scroll" className="bg-background text-[#0b1c30] antialiased overflow-x-hidden overflow-y-auto h-screen snap-y snap-mandatory scroll-smooth">
        <Hero />
        <HowItWorks />
        <Features />
        <CukaiAccountShowcase />
        <CukaiBotShowcase />
        <Pricing />
        <FAQ />
        <div className="snap-start">
          <FinalCTA />
          <Footer />
        </div>
      </div>
    </>
  );
}

export default Home;