import { useState } from 'react';

// ── Main Component ─────────────────────────────────────────────────────────────
function TermsConditions() {

  return (
    <main className="h-[calc(100vh-4.1rem)] bg-background font-body">
      <div className="mx-auto max-w-7xl space-y-6 px-6 py-6">

        {/* ── Page Header ── */}
        <div className="mb-6 flex items-start gap-3">
          <div>
            <h1 className="font-headings text-3xl font-bold tracking-tight text-headings">Terms & Conditions</h1>
            <p className="mt-1 text-sm text-[#64748B]">
              Please read these terms carefully before using our platform. They govern your access to and use of cukai.ai's services.
            </p>
          </div>
        </div>

        {/* ── Terms Content ── */}
        <section className="rounded-xl border border-[#E2E8F0] bg-white p-5">
          <div className="space-y-6 text-sm leading-relaxed text-[#334155]">
            <p>
              Welcome to cukai.ai. By accessing or using our web application, you agree to be bound by these Terms and Conditions. Our platform provides automated tools and AI-driven insights to assist you with tax-related calculations and organization. You are responsible for ensuring that all data, financial information, and inputs you provide to the platform are accurate, complete, and legally valid.
            </p>

            <p>
              Please note that cukai.ai is an artificial intelligence assistant designed for informational and estimation purposes only. The outputs, suggestions, and calculations generated by the platform do not constitute official legal, financial, or professional tax advice. You are highly encouraged to verify all results with a qualified tax professional or certified public accountant before submitting any official filings to tax authorities.
            </p>

            <p>
              We take your data privacy seriously; however, you retain ownership of the data you upload, while granting us the necessary rights to process it to deliver our services. We reserve the right to modify, suspend, or terminate your access to the web app at any time if these terms are violated. Your continued use of cukai.ai following any updates to these terms constitutes your acceptance of the revised agreement.
            </p>
          </div>
        </section>

      </div>
    </main>
  );
}

export default TermsConditions;