import { useState } from 'react';

// ── Main Component ─────────────────────────────────────────────────────────────
function TermsConditions() {

  return (
    <main className="h-[calc(100vh-4.1rem)] overflow-hidden bg-background font-body flex flex-col">
      <div className="mx-auto w-full max-w-7xl px-6 py-4 flex flex-col flex-1 min-h-0 gap-3">

        {/* ── Page Header ── */}
        <div className="shrink-0">
          <h1 className="font-headings text-2xl font-bold tracking-tight text-headings">Terms & Conditions</h1>
          <p className="text-xs text-muted mt-1">
            Please read these terms carefully before using our platform. They govern your access to and use of cukai.ai's services.
          </p>
        </div>

        {/* ── Terms Content ── */}
        <div className="flex-1 min-h-0 overflow-y-auto">
          <section className="rounded-xl border border-border bg-surface p-4">
            <div className="space-y-6 text-sm leading-relaxed text-[#334155]">
              <p>
                Welcome to cukai.ai. By accessing or using our web application, you agree to be bound by these Terms and Conditions. Our platform provides automated tools and AI-driven insights to assist you with tax-related calculations and organization. You are responsible for ensuring that all data, financial information, and inputs you provide to the platform are accurate, complete, and legally valid.
              </p>

              <p>
                Please note that cukai.ai is an artificial intelligence assistant designed for informational and estimation purposes only. The outputs, suggestions, and calculations generated by the platform do not constitute official legal, financial, or professional tax advice. You are highly encouraged to verify all results with a qualified tax professional or certified public accountant before submitting any official filings to tax authorities.
              </p>

              <p>
                We take your data privacy seriously; however, you retain ownership of the data you upload, while granting us the necessary rights to process it to deliver our services. We reserve the right to modify, suspend, or terminate your access to the web app at any time if these terms are violated. Your continued use of cukai.ai following any updates to these terms constitutes your acceptance of the revised agreement.
              </p>
            </div>
          </section>
        </div>

      </div>
    </main>
  );
}

export default TermsConditions;